<?php

// print_r($encode);
// echo"<br>";
// print_r($decode);

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Settings</title>
</head>

<body class='container text-center mt-5 border'>
    <h2 class='alert alert-success mt-4'>Add Users</h2>
    </h2>
    <?php
    if (isset($msg)) {
        echo $msg;
    };

    ?>
    <?php echo $this->tag->form(['', 'class' => 'my-5']); ?>
    <p class="row">
        <label for="email" class='label col-2 mx-5'>Username</label>
        <?php echo $this->tag->textField(['username', 'class' => 'form-control col-6']) ?>
    </p>
   
    <p class="row">
        <label for="roles" class='label col-2 mx-5'>Roles</label>
        <?php

        $allroles = array();
        foreach ($roles as $role) {
            $allroles[$role->role] = $role->role;
        }

        echo $this->tag->select(['roles', $allroles, 'class' => 'form-control col-6']) ?>
    </p>
   


    <p>
        <?php echo $this->tag->submitButton(["Add", 'class' => 'btn  btn-primary mx-5']); ?>
    </p>
    <?php echo $this->tag->endForm(); ?>
</body>

</html>